module TraktApi; end

require 'trakt_api/version'
require 'trakt_api/configuration'
require 'trakt_api/base'
require 'trakt_api/account'
require 'trakt_api/calendar'
require 'trakt_api/comment'
require 'trakt_api/genres'
require 'trakt_api/lists'
require 'trakt_api/movies'
require 'trakt_api/network'
require 'trakt_api/recommendations'
require 'trakt_api/search'
require 'trakt_api/server'
require 'trakt_api/shows'
require 'trakt_api/client'
